services:
  app:
    build: .
    container_name: dergi_app
    ports:
      - "80:80"
    environment:
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT:-3306}
    restart: unless-stopped
